/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.border.Border;

/**
 *
 * @author Dell
 */
public class CartItem extends javax.swing.JPanel {

    private Home home;
    public void setHome(Home home){
        this.home = home;
    }
    
    private String barcode;
    public void setBarcode(String barcode){
        this.barcode = barcode;
    }
    /**
     * Creates new form CartItem
     */
    public CartItem() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(32767, 70));
        setMinimumSize(new java.awt.Dimension(610, 70));
        setPreferredSize(new java.awt.Dimension(610, 70));

        jPanel18.setBackground(new java.awt.Color(239, 242, 247));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel18MouseExited(evt);
            }
        });
        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 2, 0));
        jPanel19.setOpaque(false);
        jPanel19.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(239, 242, 247));
        jTextField1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("2");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setOpaque(true);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField1MouseExited(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel19.add(jTextField1, java.awt.BorderLayout.WEST);

        jPanel21.setOpaque(false);
        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Rose");
        jLabel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        jLabel15.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel21.add(jLabel15, java.awt.BorderLayout.LINE_START);

        jLabel16.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("100.00");
        jPanel21.add(jLabel16, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 64));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(239, 242, 247));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-25.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.LINE_END);

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("200.00");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        jPanel2.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel21.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel19.add(jPanel21, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel19, java.awt.BorderLayout.LINE_END);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Chocolate");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("1");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel1.add(jLabel2, java.awt.BorderLayout.LINE_START);

        jPanel18.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseEntered
        // TODO add your handling code here:
        jPanel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,153,255), 1, true));
    }//GEN-LAST:event_jPanel18MouseEntered

    private void jPanel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseExited
        // TODO add your handling code here:
        jPanel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239,242,247), 1, true));
    }//GEN-LAST:event_jPanel18MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.home.removeItem(this.barcode);
        this.home.loadCartItems();
        this.home.calculation();
        this.home.calculation2();
    }//GEN-LAST:event_jButton1ActionPerformed
private boolean checkKeyEvent(KeyEvent evt) {

        switch (evt.getKeyChar()) {
            case '0':
                return true;
            case '1':
                return true;
            case '2':
                return true;
            case '3':
                return true;
            case '4':
                return true;
            case '5':
                return true;
            case '6':
                return true;
            case '7':
                return true;
            case '8':
                return true;
            case '9':
                return true;
            case '.':
                return true;
            default:
                return false;
        }
    }
 private String qty ="0";
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        this.qty = jTextField1.getText();
         if (checkKeyEvent(evt)) {
            if (jTextField1.getText().equals("1.00")) {
                
                this.qty = String.valueOf(evt.getKeyChar());
            } else {
                this.qty += String.valueOf(evt.getKeyChar());
            }

        }

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DELETE:
                this.qty = "";
                break;
            case KeyEvent.VK_BACK_SPACE:
                if (this.qty.length() > 0) {
                    this.qty = this.qty.substring(0, this.qty.length() - 1);
                }
                break;
            case KeyEvent.VK_ADD:
                this.qty = String.valueOf(Double.parseDouble(qty) + 1);
                break;
            case KeyEvent.VK_SUBTRACT:
                if (Double.parseDouble(qty) > 1) {
                    this.qty = String.valueOf(Double.parseDouble(qty) - 1);
                }
                break;
            case KeyEvent.VK_MINUS:
                if (Double.parseDouble(qty) > 1) {
                    this.qty = String.valueOf(Double.parseDouble(qty) - 1);
                }
        }

        jTextField1.setText(this.qty);

        if (evt.getKeyCode() == KeyEvent.VK_ENTER&&!jTextField1.getText().isEmpty()) {
            home.updateCart(barcode, jTextField1.getText());           
        }

     
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1MouseExited

    public void setItemNumber(String number){
        jLabel2.setText(number);
    }
    
    public void setProductName(String name){
        jLabel1.setText(name);
    }
    
    
    public void setQuantity(String qty){        
        jTextField1.setText(qty);
    }
    
    public void setBrand(String brand){
        jLabel15.setText(brand);
    }
    
    public void setUnitPrice(String price){
        jLabel16.setText(price);
    }
    
    public void setTotal(String total){
        jLabel3.setText(total);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
