/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.nio.file.FileSystems;
import models.MyMethods;

/**
 *
 * @author Dell
 */
public class Product_card extends javax.swing.JPanel {

    private Product_registration product_registration;
    
    public void setProductRegistration(Product_registration product_registration){
        this.product_registration = product_registration;
    }
    /**
     * Creates new form Product_card
     */
    public Product_card() {
        initComponents();
        setLogo();
    }
    
    private void setLogo() {
        
            String userDirectory = FileSystems.getDefault().getPath("")
                    .toAbsolutePath()
                    .toString();

            String newpath = userDirectory.substring(0, userDirectory.lastIndexOf(""));

            String path = newpath + "\\src\\product_images\\clogard.jpg";
    
        jLabel1.setIcon(MyMethods.resizeImage(120, 90, path));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        setMaximumSize(new java.awt.Dimension(2000, 105));
        setMinimumSize(new java.awt.Dimension(1200, 105));
        setPreferredSize(new java.awt.Dimension(1248, 105));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel18.setBackground(new java.awt.Color(239, 242, 247));
        jPanel18.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        jPanel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel18MouseExited(evt);
            }
        });
        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(750, 60));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 100));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cream Cracker");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Munchee");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel3);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Ceylone Buiscuits Limited");
        jPanel3.add(jLabel13, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("7418529637893");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel3.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel21.setOpaque(false);
        jPanel21.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel14.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("50");
        jLabel14.setPreferredSize(new java.awt.Dimension(70, 25));
        jPanel21.add(jLabel14, java.awt.BorderLayout.LINE_START);

        jPanel22.setOpaque(false);
        jPanel22.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("50.00");
        jPanel22.add(jLabel11);

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("100.00");
        jPanel22.add(jLabel10);

        jLabel16.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("80.00");
        jPanel22.add(jLabel16);

        jPanel21.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel21, java.awt.BorderLayout.CENTER);

        add(jPanel18);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseEntered
        // TODO add your handling code here:
        jPanel18.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,255), 1), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        //jPanel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,153,255), 1, true));
    }//GEN-LAST:event_jPanel18MouseEntered

    private void jPanel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseExited
        // TODO add your handling code here:
        jPanel18.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        //jPanel18.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
    }//GEN-LAST:event_jPanel18MouseExited

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        // TODO add your handling code here:
        product_registration.setProductDetails(jLabel4.getText());
        product_registration.disableBarcodeField();
    }//GEN-LAST:event_jPanel18MouseClicked

    //data setters to the card
    public void setImage(String image){
        
          String userDirectory = FileSystems.getDefault().getPath("")
                    .toAbsolutePath()
                    .toString();

            String newpath = userDirectory.substring(0, userDirectory.lastIndexOf(""));

            String path = newpath + "\\product_image\\"+image;
      
        jLabel1.setIcon(MyMethods.resizeImage(120, 90, path));
    }
    
    public void setProductName(String name){
        jLabel2.setText(name);
    }
    
    public void setBrand(String brand){
        jLabel3.setText(brand);
    }
    
    public void setCompany(String company){
        jLabel13.setText(company);
    }
    
    public void setBarcode(String barcode){
        jLabel4.setText(barcode);
    }
    
    public void setQuantity(String qty){
        jLabel14.setText(qty);
    }
    
    public void setBuyingPrice(String price){
        jLabel11.setText(price);
    }
    
    public void setOurPrice(String price){
        jLabel10.setText(price);
    }
    
    public void setUnitPrice(String price){
        jLabel16.setText(price);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
