/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import static gui.Customer_registration.logger;
import java.io.FileReader;
import java.nio.file.FileSystems;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;
import models.MyMethods;
import models.Mysql;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Dell
 */
public class WholeSaleHistory extends javax.swing.JPanel {

    /**
     * Creates new form WholeSaleHistory
     */
    public WholeSaleHistory() {
        initComponents();
       
        jTextField2.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        loadInvoice();
    }

    private void loadInvoice() {

        try {

            double total = 0;
            String invoid = jTextField1.getText();

            String date = jTextField2.getText();

            ResultSet results = Mysql.execute("SELECT * FROM `whole_sale_invoice`  WHERE id LIKE '%" + invoid + "%'  AND datetime LIKE '%" + date + "%'    ");
            DefaultTableModel mode = (DefaultTableModel) jTable1.getModel();
            mode.setNumRows(0);
            int count = 0;
            
            double pending = 0;

            while (results.next()) {

                Vector<String> v = new Vector<>();
                ResultSet results1 = Mysql.execute("SELECT * FROM `whole_sale_invoice_item`  WHERE `invoice_id` = '" + results.getString("id") + "'   ");

                while (results1.next()) {
                    total += results1.getDouble("quantity") * results1.getDouble("price");

                }
                
                if(results.getDouble("payment")<0){
                    pending += results.getDouble("payment");
                }

                v.add(results.getString("id"));
                v.add(results.getString("datetime"));
                v.add(results.getString("payment"));

                v.add(String.valueOf(total));
                total = 0;
                mode.addRow(v);
                count++;

            }
            jLabel1.setText("Invoices ( " + count + " )");
            jLabel7.setText(""+pending);
            jTable1.setModel(mode);

        } catch (Exception e) {
            logger.log(Level.WARNING, "load wholesale invoice history table", e);
            e.printStackTrace();
        }

    }

    private void loadInvoiceitem() {

        try {

            int row = jTable1.getSelectedRow();
            DefaultTableModel mode = (DefaultTableModel) jTable2.getModel();
            mode.setNumRows(0);
            if (row != -1) {

                double total = 0;

                ResultSet results = Mysql.execute("SELECT * FROM `whole_sale_invoice_item`  WHERE  `invoice_id`='" + jTable1.getValueAt(row, 0) + "' ");

                int count = 0;

                while (results.next()) {

                    Vector<String> v = new Vector<>();

                    v.add(results.getString("product_name"));
                    v.add(results.getString("quantity"));
                    v.add(results.getString("price"));

                    total = Double.parseDouble(results.getString("quantity")) * Double.parseDouble(results.getString("price"));
                    v.add(String.valueOf(total));
                    mode.addRow(v);
                    count++;

                }
                jLabel2.setText("Invoice item ( " + count + " )");

                jTable2.setModel(mode);
            }

        } catch (Exception e) {
            logger.log(Level.WARNING, "load wholesale invoice item history table", e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setMinimumSize(new java.awt.Dimension(321, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(1069, 200));
        jPanel1.setLayout(new java.awt.BorderLayout(15, 0));

        jPanel3.setMinimumSize(new java.awt.Dimension(212, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(320, 300));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setPreferredSize(new java.awt.Dimension(320, 250));
        jPanel5.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search invoices");
        jPanel5.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Invoice ID");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel9.add(jLabel3, java.awt.BorderLayout.LINE_START);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel9.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Date");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel10.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel10.add(jTextField2, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel10);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout(5, 0));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search invoices");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, java.awt.BorderLayout.CENTER);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload1.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(45, 31));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel6);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("Pending payments -");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("0");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Invoices (0)");
        jPanel4.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Date & Time", "Paid amount", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(1069, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Invoice item (0)");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jTable2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product name", "Quantity", "Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setBottomComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        loadInvoice();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        loadInvoice();
        loadInvoiceitem();
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        loadInvoice();
        loadInvoiceitem();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loadInvoice();
        loadInvoiceitem();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        loadInvoiceitem();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void reset(){
        jTable1.clearSelection();
        jTextField1.setText("");       
        jTextField2.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        loadInvoice();
        loadInvoiceitem();
    }
   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

            double netTotal = 0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                netTotal += Double.parseDouble(String.valueOf(jTable1.getValueAt(i, 3)));
            }

            //            WE CAN USE ONLY NEDBEANS IDE
//            String userDirectory = FileSystems.getDefault().getPath("").toAbsolutePath().toString();
//
//            String url = userDirectory + "\\src\\reports\\wikrama_sale_invoice_report.jasper";
//
//            String tempUrl = "src/reports/wikrama_sale_invoice_report.jasper"; // for testing
//            String suburl = "src/reports/wikrama_sale_invoice_items.jasper"; // for testing
//            
//             WE CAN USE AFTER BUILD
            String userDirectory = FileSystems.getDefault()
                    .getPath("")
                    .toAbsolutePath()
                    .toString();

            String newpath = userDirectory.substring(0, userDirectory.lastIndexOf("\\"));
//            System.out.println(newpath);

            String tempUrl = newpath + "\\src\\reports\\wikrama_sale_invoice_report.jasper";
            String suburl = newpath + "\\src\\reports\\wikrama_sale_invoice_items.jasper";

//accessng JSON config file - start
            String JSONurl = userDirectory + "\\lib\\databs.json";
            Object obj = new JSONParser().parse(new FileReader(JSONurl));
            JSONObject j = (JSONObject) obj;

            String db = String.valueOf(j.get("databaseName"));
            String username = String.valueOf(j.get("username"));
            String password = String.valueOf(j.get("password"));

//accessng JSON config file - end
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + db, username, password);

            java.util.HashMap<String, Object> parameters = new HashMap<>();

            parameters.put("Parameter5", String.valueOf(netTotal));
            parameters.put("Parameter7", date);
            parameters.put("Parameter4", jLabel7.getText()); //pending payments
            

            JRTableModelDataSource datasource = new JRTableModelDataSource(jTable1.getModel());

            JasperFillManager.fillReport(suburl, parameters, connection);
            JasperPrint report = JasperFillManager.fillReport(tempUrl, parameters, datasource);
            //JasperPrintManager.printReport(report, false); //prirent report dirrectly
            JasperViewer.viewReport(report, false); //for testing

        } catch (Exception e) {
            logger.log(Level.WARNING, "print_invoice_history_btn", e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
